import './globals.css'
import Sidebar from '@/app/components/sidebar'
import Header from '@/app/components/header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="jp">
      <body>
        <div className="container">
          <Sidebar/>

          <div className='main-header'>
            <header style={{ zIndex: '10'}}>
              <Header />
            </header>

            <main>
              {children}
            </main>
          </div>
          
        </div>
      </body>
    </html>
  )
}